### ISSUE TITLE
Practica 5_Reconocimiento de patrón Hiro

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo_prestadores-de-servicios#1]
[Practica 5_Reconocimiento de patron Hiro.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo_prestadores-de-servicios/files/8600639/Practica.5_Reconocimiento.de.patron.Hiro.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Buen trabajo
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
